version: '3'
services:
  app:
    image: your_username/my-node-app:latest
    container_name: my-node-app
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: some-postgres-new
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork: