name: Publish Docker Image

# Событие на создание релиза
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонировать код из репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Настроить Docker Buildx для сборки
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Шаг 3: Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 4: Собрать и запушить Docker-образ
      - name: Build and push Docker image
        run: |
          docker build -t your_username/my-node-app:${{ github.ref_name }} .
          docker push your_username/my-node-app:${{ github.ref_name }}

