name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонировать код из репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Пуш Docker-образа (например, v1.0.0)
      - name: Push Docker image
        run: |
          docker push pankeit/my-node-app:${{ github.ref_name }}
